CREATE TABLE brdgInstructors(instructorId INTEGER, peopleId INTEGER, tutorialEventId INTEGER);
CREATE TABLE brdgMediaCallsEvents(mediumEventId INTEGER, mediumId INTEGER, eventId INTEGER, rank INTEGER);
CREATE TABLE brdgMediaPresentations(mediumPresentationId INTEGER, mediumId INTEGER, presentationId INTEGER, rank INTEGER);
CREATE TABLE brdgOrganizersAttendees(organizerAttendeeId INTEGER, peopleId INTEGER, eventId INTEGER, "type" VARCHAR);
CREATE TABLE brdgPresentationsEvents(presentationEventId INTEGER, presentationId INTEGER, eventId INTEGER, date DATE);
CREATE TABLE brdgPresenters(peopleId INTEGER, presentationEventId INTEGER, presenterId INTEGER);
CREATE TABLE brdgPublicationsEvents(publicationEventId INTEGER, publicationId INTEGER, eventId INTEGER);
CREATE TABLE brdgTutorialsEvents(tutorialEventId INTEGER, tutorialId INTEGER, eventId INTEGER, fromDate DATE, toDate DATE);
CREATE TABLE brdgVenue(eventLocationId INTEGER, eventId INTEGER, locationId INTEGER);
CREATE TABLE tblCallsEvents(eventId INTEGER, title VARCHAR, startDate DATE, endDate DATE, description VARCHAR, "type" VARCHAR, ivlweb BOOLEAN, cnsweb BOOLEAN);
CREATE TABLE tblPresentations(presentationId INTEGER, title VARCHAR, additionalInfo VARCHAR, "type" VARCHAR, ivlweb BOOLEAN, cnsweb BOOLEAN);
CREATE TABLE tblWorkshops(id INTEGER, title VARCHAR, link VARCHAR, start_date DATE, end_date DATE, city VARCHAR, state VARCHAR, country VARCHAR);
CREATE TABLE vwDebugBryanPresentations(mediumId INTEGER, mediumPresentationId INTEGER, rank INTEGER, fileNameURL VARCHAR, mediumtype VARCHAR, title VARCHAR, presentationtype VARCHAR);
CREATE TABLE vwEventAttendees(eventId INTEGER, attendees VARCHAR);
CREATE TABLE vwEventOrganizers(eventId INTEGER, organizers VARCHAR);
CREATE TABLE vwEventsPresentations(eventId INTEGER, presentationId INTEGER, date DATE, title VARCHAR, fileNameURL VARCHAR, "type" VARCHAR);
CREATE TABLE vwEventsURL(eventId INTEGER, title VARCHAR, fileNameURL VARCHAR, "type" VARCHAR);
CREATE TABLE vwEventsURLs(eventId INTEGER, title VARCHAR, fileNameURL VARCHAR, "type" VARCHAR);
CREATE TABLE vwIVLEventsAll(eventId INTEGER, title VARCHAR, startDate DATE, endDate DATE, description VARCHAR, eventtype VARCHAR, organizers VARCHAR, attendees VARCHAR, fileNameURL VARCHAR, filetype VARCHAR, city VARCHAR, StateProvince VARCHAR, "year" DOUBLE, Country VARCHAR, presentationId INTEGER, pretitle VARCHAR, prefilenameurl VARCHAR, presenters VARCHAR, typeorder INTEGER);
CREATE TABLE vwIVLPresentationsAll(presentationId INTEGER, presentationtitle VARCHAR, additionalInfo VARCHAR, presentationtype VARCHAR, date DOUBLE, exactdate DATE, eventstitle VARCHAR, eventurl VARCHAR, presenters VARCHAR, city VARCHAR, StateProvince VARCHAR, Country VARCHAR, fileNameURL VARCHAR, mediatype VARCHAR);
CREATE TABLE vwIVLTeachingEducPresentations(presentationId INTEGER, presentationtitle VARCHAR, additionalInfo VARCHAR, presentationtype VARCHAR, date DOUBLE, exactdate DATE, eventstitle VARCHAR, eventurl VARCHAR, presenters VARCHAR, city VARCHAR, StateProvince VARCHAR, fileNameURL VARCHAR, mediatype VARCHAR);
CREATE TABLE vwIVLWorkshops(id INTEGER, title VARCHAR, link VARCHAR, start_date DATE, end_date DATE, city VARCHAR, state VARCHAR, country VARCHAR);
CREATE TABLE vwPresentationEventPresenters(presentationEventId INTEGER, presenters VARCHAR);
CREATE TABLE vwTutorialEventPresenters(tutorialEventId INTEGER, presenters VARCHAR);
