CREATE TABLE brdgAuthorsEditors(authorEditorId INTEGER, peopleId INTEGER, publicationId INTEGER, rank INTEGER, "type" VARCHAR);
CREATE TABLE brdgMediaPublications(mediumPublicationId INTEGER, mediumId INTEGER, publicationId INTEGER, rank INTEGER);
CREATE TABLE brdgPublicationsEvents(publicationEventId INTEGER, publicationId INTEGER, eventId INTEGER);
CREATE TABLE brdgResearchPublications(researchPublicationId INTEGER, researchId INTEGER, publicationId INTEGER);
CREATE TABLE brdgTagsPublications(tagPublicationId INTEGER, publicationId INTEGER, semanticTagId INTEGER);
CREATE TABLE tblPublications(publicationId INTEGER, publicationTitle VARCHAR, publicationDate DATE, publicationVenue VARCHAR, venueVolume VARCHAR, venueNumber VARCHAR, venuePages VARCHAR, "type" VARCHAR, publisher VARCHAR, venueChapter VARCHAR);
CREATE TABLE vwAuthorRankedWithContact(authorEditorId INTEGER, peopleId INTEGER, fName VARCHAR, mName VARCHAR, lName VARCHAR, homepage VARCHAR, publicationId INTEGER, rank INTEGER, "type" VARCHAR);
CREATE TABLE vwAuthorsRanked(authorEditorId INTEGER, peopleId INTEGER, publicationId INTEGER, rank INTEGER, "type" VARCHAR);
CREATE TABLE vwEditorRankedWithContact(authorEditorId INTEGER, peopleId INTEGER, fName VARCHAR, mName VARCHAR, lName VARCHAR, homepage VARCHAR, publicationId INTEGER, rank INTEGER, "type" VARCHAR);
CREATE TABLE vwIVLPublicationsAll(publicationId INTEGER, publicationTitle VARCHAR, date DOUBLE, publicationVenue VARCHAR, venueVolume VARCHAR, venueNumber VARCHAR, venuePages VARCHAR, "type" VARCHAR, publisher VARCHAR, venueChapter VARCHAR, authors VARCHAR, editors VARCHAR, fileNameURL VARCHAR, linktype VARCHAR, typeorder INTEGER, "year" VARCHAR);
CREATE TABLE vwPublicationAuthors(publicationId INTEGER, authors VARCHAR);
CREATE TABLE vwPublicationEditors(publicationId INTEGER, editors VARCHAR);
